const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getMarchi: () => ipcRenderer.invoke('get-marchi'),
  addMarchio: (marchio) => ipcRenderer.invoke('add-marchio', marchio),
  updateMarchio: (marchio) => ipcRenderer.invoke('update-marchio', marchio),
  deleteMarchio: (id) => ipcRenderer.invoke('delete-marchio', id),
  generateBitly: (url) => ipcRenderer.invoke('generate-bitly', url),
  convertTinyUrl: (url) => ipcRenderer.invoke('convert-tinyurl', url),
  testLink: (url) => ipcRenderer.invoke('test-link', url),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSetting: (key, value) => ipcRenderer.invoke('set-setting', key, value),
  getTemplates: () => ipcRenderer.invoke('get-templates'),
  saveTemplates: (templates) => ipcRenderer.invoke('save-templates', templates),
  generateFiles: (data) => ipcRenderer.invoke('generate-files', data),
  saveFile: (data) => ipcRenderer.invoke('save-file', data),
  exportMarchi: () => ipcRenderer.invoke('export-marchi'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (_, data) => callback(data)),
  onUpdateProgress: (callback) => ipcRenderer.on('update-progress', (_, data) => callback(data)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', (_, data) => callback(data)),
  onUpdateNotAvailable: (callback) => ipcRenderer.on('update-not-available', () => callback()),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (_, data) => callback(data)),
});